language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6.1"
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - redis-server
script:
  - bundle exec rake rubocop
  - COVERBAND_HASH_REDIS_STORE=t bundle exec rake
  - COVERBAND_HASH_REDIS_STORE=t bundle exec rake forked_tests
  - bundle exec rake
  - bundle exec rake forked_tests
  # remove this for now as it is flaky
  # passes locally on 2.3.5 on travis passes sometimes on 2.4 and always on 2.6.1
  #- bundle exec rake benchmarks:memory
  - bundle exec rake benchmarks
